// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFRqEnmsSliPYO54uii_qNmNqpBYjv2M',
    appId: '1:426944817623:web:61f1ab147c8c97a1174392',
    messagingSenderId: '426944817623',
    projectId: 'saas-manu-project',
    authDomain: 'saas-manu-project.firebaseapp.com',
    storageBucket: 'saas-manu-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2X0o9PHJSgeoroFwWAhU_De461jbj3Dg',
    appId: '1:426944817623:android:08ea1d65ef3e0c15174392',
    messagingSenderId: '426944817623',
    projectId: 'saas-manu-project',
    storageBucket: 'saas-manu-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYI0z5X0tnBzWQc8aVYZjy3Z_pdAGfPs',
    appId: '1:426944817623:ios:46b2ddfa67a143a8174392',
    messagingSenderId: '426944817623',
    projectId: 'saas-manu-project',
    storageBucket: 'saas-manu-project.firebasestorage.app',
    iosBundleId: 'com.example.saasManu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYI0z5X0tnBzWQc8aVYZjy3Z_pdAGfPs',
    appId: '1:426944817623:ios:46b2ddfa67a143a8174392',
    messagingSenderId: '426944817623',
    projectId: 'saas-manu-project',
    storageBucket: 'saas-manu-project.firebasestorage.app',
    iosBundleId: 'com.example.saasManu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFRqEnmsSliPYO54uii_qNmNqpBYjv2M',
    appId: '1:426944817623:web:eebc73390eba0e82174392',
    messagingSenderId: '426944817623',
    projectId: 'saas-manu-project',
    authDomain: 'saas-manu-project.firebaseapp.com',
    storageBucket: 'saas-manu-project.firebasestorage.app',
  );
}
